# Generated by Django 2.0.3 on 2018-12-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_lowwpm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lowwpm',
            new_name='high_wpm',
        ),
        migrations.AddField(
            model_name='profile',
            name='low_wpm',
            field=models.IntegerField(default=0),
        ),
    ]
