# Generated by Django 2.1.3 on 2018-12-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181205_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordspermin',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='WordsPerMin',
        ),
    ]
